name: Test package build

env:
  PACKAGE_NAME: ${{ github.event.repository.name }}

on:
  pull_request:
    branches:
      - main
  push:
  workflow_dispatch:

# We use a matrix to run the same job on multiple operating systems and Python versions.
jobs:
  test-os:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }} with minconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
      - name: Print Python Version
        run: |
          python -V
      - name: Install ${{ env.PACKAGE_NAME }}
        run: |
          pip install .
      - name: Test ${{ env.PACKAGE_NAME }} install
        run: |
          python -c "import ${PACKAGE_NAME}"
